# Generated by Django 3.1.2 on 2020-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=200)),
                ('Date_of_Birth', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
